In [2]:
import numpy as np

Basic array creations

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [12]:
a = [1.8,2,3.5]

In [13]:
a

[1.8, 2, 3.5]

In [14]:
np.array(a)

array([1.8, 2. , 3.5])

In [15]:
b = [[1,2,3],[4,2,3]]
b

[[1, 2, 3], [4, 2, 3]]

In [16]:
np.array(b)

array([[1, 2, 3],
       [4, 2, 3]])

arrays generation function

In [21]:
arr = np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [24]:
arr = np.zeros((9,9))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr = np.ones((4,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
arr = np.linspace(1,50,1000)
arr

array([ 1.        ,  1.04904905,  1.0980981 ,  1.14714715,  1.1961962 ,
        1.24524525,  1.29429429,  1.34334334,  1.39239239,  1.44144144,
        1.49049049,  1.53953954,  1.58858859,  1.63763764,  1.68668669,
        1.73573574,  1.78478478,  1.83383383,  1.88288288,  1.93193193,
        1.98098098,  2.03003003,  2.07907908,  2.12812813,  2.17717718,
        2.22622623,  2.27527528,  2.32432432,  2.37337337,  2.42242242,
        2.47147147,  2.52052052,  2.56956957,  2.61861862,  2.66766767,
        2.71671672,  2.76576577,  2.81481481,  2.86386386,  2.91291291,
        2.96196196,  3.01101101,  3.06006006,  3.10910911,  3.15815816,
        3.20720721,  3.25625626,  3.30530531,  3.35435435,  3.4034034 ,
        3.45245245,  3.5015015 ,  3.55055055,  3.5995996 ,  3.64864865,
        3.6976977 ,  3.74674675,  3.7957958 ,  3.84484484,  3.89389389,
        3.94294294,  3.99199199,  4.04104104,  4.09009009,  4.13913914,
        4.18818819,  4.23723724,  4.28628629,  4.33533534,  4.38

random generation functions

In [29]:
np.random.rand(10)

array([0.70506612, 0.03884915, 0.05352412, 0.71816943, 0.67391822,
       0.24895678, 0.6239141 , 0.56143997, 0.07022402, 0.8542702 ])

In [30]:
np.random.randn(5)

array([-0.4306765 ,  0.23579455,  0.61984612, -1.47709433, -1.71603687])

In [31]:
np.random.randint(10)

3

In [32]:
np.random.randint(10,20,198)

array([17, 19, 18, 11, 17, 19, 16, 19, 14, 19, 10, 10, 18, 14, 12, 19, 14,
       14, 16, 18, 17, 16, 16, 12, 15, 17, 19, 14, 10, 15, 10, 18, 18, 17,
       10, 16, 19, 10, 18, 17, 17, 12, 11, 11, 13, 14, 17, 11, 19, 13, 16,
       11, 16, 14, 17, 16, 16, 14, 17, 12, 12, 18, 11, 12, 17, 18, 19, 17,
       13, 13, 15, 14, 17, 18, 13, 18, 18, 10, 15, 16, 17, 13, 13, 11, 18,
       19, 19, 17, 11, 19, 19, 16, 12, 16, 18, 19, 17, 18, 18, 11, 13, 17,
       17, 14, 18, 18, 17, 10, 14, 13, 10, 19, 14, 17, 16, 15, 19, 11, 18,
       12, 12, 18, 10, 10, 10, 14, 17, 13, 17, 11, 15, 16, 17, 13, 18, 11,
       12, 10, 15, 13, 18, 16, 18, 19, 12, 18, 10, 19, 18, 12, 18, 18, 17,
       19, 16, 11, 17, 11, 17, 18, 17, 16, 16, 11, 15, 17, 16, 14, 11, 13,
       10, 10, 15, 11, 14, 18, 10, 11, 19, 18, 19, 15, 15, 13, 11, 19, 13,
       14, 13, 10, 13, 15, 16, 13, 17, 12, 11, 16], dtype=int32)

arrays attribute

In [33]:
arr = np.array([[1,2,3],[1,2,3],[5,4,2]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [5, 4, 2]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [36]:
arr.dtype

dtype('int64')

arrays methods

In [37]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [5, 4, 2]])

In [38]:
arr.min()

np.int64(1)

In [39]:
arr.max()

np.int64(5)

In [40]:
arr.sum()

np.int64(23)

when we have to calculate sum across coloum

In [44]:
np.sum(arr,axis = 0) 

array([7, 8, 8])

when we have to calcute sum across rows

In [45]:
np.sum(arr,axis = 1)

array([ 6,  6, 11])

In [46]:
arr.mean()

np.float64(2.5555555555555554)

In [47]:
arr.std()

np.float64(1.2570787221094177)

index of max and min

In [48]:
arr.argmax()

np.int64(6)

In [49]:
arr.argmin()

np.int64(0)

reshaping and resizing

In [50]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr = arr.reshape(5,6)

In [53]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

numpy indexing and slicing of vectors

In [55]:
arr = np.arange(20,31)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr[4]

np.int64(24)

In [58]:
arr[0:7]

array([20, 21, 22, 23, 24, 25, 26])

In [59]:
arr[0::2]

array([20, 22, 24, 26, 28, 30])

Indexing and slicing of matrix

In [4]:
import numpy as np

In [6]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[4]

array([21, 22, 23, 24, 25])

In [8]:
arr[0,0]

np.int64(1)

In [9]:
arr[5,4]

np.int64(30)

In [11]:
slice = arr[0:2,2:4]
slice

array([[3, 4],
       [8, 9]])

In [13]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [14]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [15]:
arr[4,:]

array([21, 22, 23, 24, 25])

Boollean indexing

In [16]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [18]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

array operations

In [20]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [21]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [22]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [23]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [24]:
a1 /a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [25]:
a1 // a2

array([0, 0, 0, 0, 0])

In [26]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [27]:
l = [10,20,30,40,50]
arr = np.array(l)

In [28]:
arr + 10

array([20, 30, 40, 50, 60])

In [29]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr2 + 20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

Deep and shallow copy 

In [58]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
slice = a[:5] 
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:

a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
b = a.copy() 
b[1] = 45
b

array([10, 45,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

matrix operations

In [75]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [76]:
A

array([[1, 2],
       [3, 4]])

In [77]:
B

array([[5, 6],
       [7, 8]])

In [78]:
A@B

array([[19, 22],
       [43, 50]])

In [79]:
A.T

array([[1, 3],
       [2, 4]])

Advance array manipulation

Stacking arrays

In [82]:
aa = np.array([1,2,3,4,5,6])
bb = np.array([7,8,9,10,11,12])
np.vstack((aa,bb))
np.hstack((aa,bb))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
np.column_stack((aa,bb))

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [85]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [89]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]